### PR TITLE
Implemented --summary parameter

### PR DESCRIPTION
**Pull request by PetrovskYYY**
Ouptuts summary by source type.

Signed-off-by: Yuriy Petrovskiy <yuriy.petrovskiy@gmail.com>

### CODE REVIEW

**Comment by MohammedRashad** [comment]
is this pull request active ? can I help with it?

**Comment by rjw245** [comment]
Was looking for this feature today. Would be nice to have the conflicts resolved and merge it.

**Comment by roskakori** [comment]
I've merged this for now though it seems I messed by the connection to the PR when renaming my merge branch when resolving the conflict. Sorry for that, I never merged a conflicting external branch before.

So technically I have to close this PR. Nevertheless the code is part of the official repository now.

**Comment by roskakori** [comment]
Merged this with #29.

As I reworked the code and changed the command line option to `--format=summary` none of the code from @PetrovskYYY actually is in the current code base. But he still features in the commit history and has an honorable mention in the README. Thanks for the effort!

**Pull request merged**
